### ISSUE TITLE
simple video player

### ISSUE THREAD

**Issue by ghost** [CodeSailer/GIF-Studio#1]
hi

I tried this example

https://codesailer.com/tutorials/simple_video_player/

But in visual studio 2022, the video player doesn't play (black screen) when enabling this line:

`this.KeyPreview = true;`

If I remove that line, the video plays again

But i can't make the key event work this way :(

can you please help?

**Comment by CodeSailer** [comment]
I'll give a look :)

Thanks for the feedback.

**Comment by CodeSailer** [comment]
I copied and pasted the code from my site in a new machine with windows 11 and visual studio 2022, everything works fine.
I tried both with a file from the local storage and from an URL(this one to be specific: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4).
The project is a "Windows Form Project", with .NET 6 LTS(Long-Term Support)

Did you get any messagge/errors in the console ?

**Comment by ghost** [comment]
I used .net 4.8 but it works using 6!

Thx
